### ISSUE TITLE
Calendar viewing pages

### ISSUE THREAD

**Issue by hingobway** [elmpoint-org/epc-next#33]
Build pages for Timeline view and Arrival/Departure view.

- [x] #163 (horizontal grid - gcal week/4day)
- [x] #174 (linear vertical - gcal schedule)
- [x] #177  (full calendar grid - gcal month)

![IMG_0668](https://github.com/user-attachments/assets/cbe56034-34f5-4b99-906a-75a927a976a5)

---

depends on
- #34
